### ISSUE TITLE
FreeBSD - Building for rdesktop-1.8.3 failed on FreeBSD 12.0-RELEASE

### ISSUE THREAD

**Issue by teisho** [rdesktop/rdesktop#297]
```
/usr/ports/net/rdesktop » sudo make MAKE_JOBS_UNSAFE=yes install clean                                                                                                                                                         
===>  Building for rdesktop-1.8.3
gmake[2]: Entering directory '/usr/ports/net/rdesktop/work/rdesktop-1.8.3'
cc -O2 -pipe  -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing  -Wall -I/usr/lib/include -I/usr/local/include -D_THREAD_SAFE -pthread  -I/usr/local/include   -I/usr/local/include -DPACKAGE_NAME=\"rdesktop\" -DPACKAGE_TARNAME=\"rdesktop\" -DPACKAGE_VERSION=\"1.8.3\" -DPACKAGE_STRING=\"rdesktop\ 1.8.3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DL_ENDIAN=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_SYS_FILIO_H=1 -DHAVE_LOCALE_H=1 -DHAVE_LANGINFO_H=1 -DHAVE_SYSEXITS_H=1 -Dssldir=\"/usr/lib\" -DHAVE_XRANDR=1 -DEGD_SOCKET=\"/var/run/egd-pool\" -DHAVE_LIBSAMPLERATE=1 -DWITH_RDPSND=1 -DRDPSND_OSS=1 -DHAVE_DIRENT_H=1 -DHAVE_DIRFD=1 -DHAVE_DECL_DIRFD=1 -DHAVE_ICONV_H=1 -DHAVE_ICONV=1 -DICONV_CONST= -DHAVE_SYS_STATVFS_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_MOUNT_H=1 -DSTAT_STATVFS=1 -DHAVE_STRUCT_STATVFS_F_NAMEMAX=1 -DIPv6=1 -DKEYMAP_PATH=\"/usr/local/share/rdesktop/keymaps/\" -o ssl.o -c ssl.c
ssl.c:91:9: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
               ^
/usr/lib/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:91:14: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
                    ^
/usr/lib/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:91:19: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
                         ^
/usr/lib/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:91:22: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
                            ^
/usr/lib/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:101:2: warning: implicit declaration of function 'BN_init' is invalid in C99 [-Wimplicit-function-declaration]
        BN_init(&mod);
        ^
ssl.c:149:24: error: incomplete definition of type 'struct x509_st'
        nid = OBJ_obj2nid(cert->cert_info->key->algor->algorithm);
                          ~~~~^
/usr/lib/include/openssl/ossl_typ.h:120:16: note: forward declaration of 'struct x509_st'
typedef struct x509_st X509;
               ^
ssl.c:153:24: error: incomplete definition of type 'struct x509_st'
                ASN1_OBJECT_free(cert->cert_info->key->algor->algorithm);
                                 ~~~~^
/usr/lib/include/openssl/ossl_typ.h:120:16: note: forward declaration of 'struct x509_st'
typedef struct x509_st X509;
               ^
ssl.c:154:7: error: incomplete definition of type 'struct x509_st'
                cert->cert_info->key->algor->algorithm = OBJ_nid2obj(NID_rsaEncryption);
                ~~~~^
/usr/lib/include/openssl/ossl_typ.h:120:16: note: forward declaration of 'struct x509_st'
typedef struct x509_st X509;
               ^
ssl.c:204:24: error: incomplete definition of type 'struct rsa_st'
        if ((BN_num_bytes(rkey->e) > (int) max_exp_len) ||
                          ~~~~^
/usr/lib/include/openssl/bn.h:181:40: note: expanded from macro 'BN_num_bytes'
# define BN_num_bytes(a) ((BN_num_bits(a)+7)/8)
                                       ^
/usr/lib/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
ssl.c:205:24: error: incomplete definition of type 'struct rsa_st'
            (BN_num_bytes(rkey->n) > (int) max_mod_len))
                          ~~~~^
/usr/lib/include/openssl/bn.h:181:40: note: expanded from macro 'BN_num_bytes'
# define BN_num_bytes(a) ((BN_num_bits(a)+7)/8)
                                       ^
/usr/lib/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
ssl.c:209:22: error: incomplete definition of type 'struct rsa_st'
        len = BN_bn2bin(rkey->e, exponent);
                        ~~~~^
/usr/lib/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
ssl.c:211:22: error: incomplete definition of type 'struct rsa_st'
        len = BN_bn2bin(rkey->n, modulus);
                        ~~~~^
/usr/lib/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
ssl.c:232:11: error: variable has incomplete type 'HMAC_CTX' (aka 'struct hmac_ctx_st')
        HMAC_CTX ctx;
                 ^
/usr/lib/include/openssl/ossl_typ.h:102:16: note: forward declaration of 'struct hmac_ctx_st'
typedef struct hmac_ctx_st HMAC_CTX;
               ^
ssl.c:233:2: warning: implicit declaration of function 'HMAC_CTX_init' is invalid in C99 [-Wimplicit-function-declaration]
        HMAC_CTX_init(&ctx);
        ^
ssl.c:235:2: warning: implicit declaration of function 'HMAC_CTX_cleanup' is invalid in C99 [-Wimplicit-function-declaration]
        HMAC_CTX_cleanup(&ctx);
        ^
3 warnings and 12 errors generated.
gmake[2]: *** [Makefile:161: ssl.o] Error 1
gmake[2]: Leaving directory '/usr/ports/net/rdesktop/work/rdesktop-1.8.3'
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/net/rdesktop
*** Error code 1

Stop.
make: stopped in /usr/ports/net/rdesktop

```

**Comment by uglym8** [comment]
I can confirm that v1.8.4, indeed, builds fine on FreeBSD 12.0-RELEASE.

Building current master will require #301 to be merged beforehand.

See also PR #302  for building the master on FreeBSD with CredSSP support without having to specify smth like 
<pre>
GSSAPI_LIBS=-lgss GSSAPI_CFLAGS=-I/usr/local/include ./configure
</pre>

**Comment by uglym8** [comment]
@teisho, could you please also check #302 if you got a spare moment (you'll need to install gss package though before running ./configure script).

**Comment by teisho** [comment]
@uglym8, Sorry for the delay. Yes I was able to build v1.8.4 on my system.

**Comment by uglym8** [comment]
Closing as fixed then:)

**Comment by teisho** [comment]
Could you please also update the version in the FreeBSD Ports? :)

**Comment by uglym8** [comment]
I guess you'd better contact the port maintainer (according to the port's Makefile: greg@hugops.pw) to do this.

Point him to this issue to additionally get rid of "--disable-credssp" line as well.
I don't know the requirements/procedures to edit the `ports` entry yet:)

**Comment by gregf** [comment]
We have had ongoing issues getting this port to work, but with the new release I think everything is ready to roll. I'll be sure to get it updated this week sometime soon as I can.

**Comment by gregf** [comment]
Oh actually it looks like this was fixed with a patch to ./configure.ac I missed that above. I was wrong about a missing dependency. Is there anyway you could cut a 1.8.5 or something to include this patch?

**Comment by hean01-cendio** [comment]
@gregf @uglym8 I will not roll a 1.8.5 release for this fix. If you want to package right now, patch release 1.8.4 source during packaging.

We will release rdesktop 1.9.0 within 1½ week or soo.
