### ISSUE TITLE
Compilation error with openssl version "0.9.8"

### ISSUE THREAD

**Issue by gilbsfr24** [rdesktop/rdesktop#220]
On a old "Hp ThinClient" with openssl version "0.9.8"  : compilation error

ssl.o: In function `rdssl_cert_to_rkey':
ssl.c:189: undefined reference to `X509_PUBKEY_get0_param'
ssl.c:206: undefined reference to `X509_PUBKEY_set0_param'
collect2: ld returned 1 exit status
make: *** [rdesktop] Erreur 1

**Comment by hean01-cendio** [comment]
We have moved from OpenSSL to GnuTLS which renders this issue invalid

**Comment by alex-eri** [comment]
1.8.3 works with openssl version "0.9.8"
