### ISSUE TITLE
master fails to compile with gnutls 3.3.29

### ISSUE THREAD

**Issue by opoplawski** [rdesktop/rdesktop#316]
rdesktop master fails to compile on EL7 with gnutls 3.3.29-8 with:
```
utils.c: In function '_utils_cert_get_status_report':
utils.c:850:15: error: 'GNUTLS_CERT_PURPOSE_MISMATCH' undeclared (first use in this function)
  if (status & GNUTLS_CERT_PURPOSE_MISMATCH) {
               ^
```
It would be good if configure checked for the necessary gnutls version if 3.3 isn't going to be supported.

**Comment by CendioOssman** [comment]
The goal was 3.2, but it seems we missed that. I'll have a look.

**Comment by CendioOssman** [comment]
Thanks. Fixed in a4bdfcfe76b4d39c2d6fd7c8c5be4af90dd4b82d.

**Comment by opoplawski** [comment]
Looks good here - thanks!
