### ISSUE TITLE
OpenSSL Error , when installing on MAC

### ISSUE THREAD

**Issue by NomiJ** [rdesktop/rdesktop#53]
MacBook-Air:rdesktop-1.8.3 nomi$ ./configure   --with-openssl=../openssl-1.1.0-pre6 --disable-credssp
checking build system type... i686-apple-darwin15.6.0
checking host system type... i686-apple-darwin15.6.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for X... libraries /usr/X11/lib, headers /usr/X11/include
checking whether -R must be followed by a space... neither works
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking for pkg-config... /opt/local/bin/pkg-config
checking for library containing socket... none required
checking for library containing inet_aton... none required
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/modem.h usability... no
checking sys/modem.h presence... no
checking for sys/modem.h... no
checking sys/filio.h usability... yes
checking sys/filio.h presence... yes
checking for sys/filio.h... yes
checking sys/strtio.h usability... no
checking sys/strtio.h presence... no
checking for sys/strtio.h... no
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking sysexits.h usability... yes
checking sysexits.h presence... yes
checking for sysexits.h... yes
checking for strip... strip
checking for OpenSSL directory... ../openssl-1.1.0-pre6
checking for pkg-config... (cached) /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for XRANDR... no
checking PCSC/pcsclite.h usability... yes
checking PCSC/pcsclite.h presence... yes
checking for PCSC/pcsclite.h... yes
checking for old version of PCSC... no
checking if architecture needs alignment... no
checking sys/soundcard.h usability... no
checking sys/soundcard.h presence... no
checking for sys/soundcard.h... no
checking dmedia/audio.h usability... no
checking dmedia/audio.h presence... no
checking for dmedia/audio.h... no
checking sys/audioio.h usability... no
checking sys/audioio.h presence... no
checking for sys/audioio.h... no
checking for LIBAO... no
checking for ALSA... no
checking for LIBSAMPLERATE... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for dirfd... yes
checking whether dirfd is declared... yes
checking whether dirfd is a macro... no
checking iconv.h usability... yes
checking iconv.h presence... yes
checking for iconv.h... yes
checking for iconv... yes
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char \* *inbuf, size_t *inbytesleft, char \* *outbuf, size_t *outbytesleft);
checking for socklen_t... yes
checking sys/vfs.h usability... no
checking sys/vfs.h presence... no
checking for sys/vfs.h... no
checking sys/statvfs.h usability... yes
checking sys/statvfs.h presence... yes
checking for sys/statvfs.h... yes
checking sys/statfs.h usability... no
checking sys/statfs.h presence... no
checking for sys/statfs.h... no
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking for sys/mount.h... yes
configure: checking how to get filesystem space usage...
checking statvfs64 function (SVR4)... no
checking statvfs function (SVR4)... yes
checking for struct statfs.f_namemax... no
checking for struct statvfs.f_namemax... yes
checking for struct statfs.f_namelen... no
checking for struct statvfs.f_namelen... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking mntent.h usability... no
checking mntent.h presence... no
checking for mntent.h... no
checking for setmntent... no
configure: creating ./config.status
config.status: creating Makefile

**Not sure how to fix this**

gcc -g -O2 -Wall -I../openssl-1.1.0-pre6/include    -I/usr/X11/include -DPACKAGE_NAME=\"rdesktop\" -DPACKAGE_TARNAME=\"rdesktop\" -DPACKAGE_VERSION=\"1.8.3\" -DPACKAGE_STRING=\"rdesktop\ 1.8.3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DL_ENDIAN=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_SYS_FILIO_H=1 -DHAVE_LOCALE_H=1 -DHAVE_LANGINFO_H=1 -DHAVE_SYSEXITS_H=1 -Dssldir=\"../openssl-1.1.0-pre6\" -DWITH_SCARD=1 -DEGD_SOCKET=\"/var/run/egd-pool\" -DWITH_RDPSND=1 -DHAVE_DIRENT_H=1 -DHAVE_DIRFD=1 -DHAVE_DECL_DIRFD=1 -DHAVE_ICONV_H=1 -DHAVE_ICONV=1 -DICONV_CONST= -DHAVE_SYS_STATVFS_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_MOUNT_H=1 -DSTAT_STATVFS=1 -DHAVE_STRUCT_STATVFS_F_NAMEMAX=1 -DKEYMAP_PATH=\"/usr/local/share/rdesktop/keymaps/\" -o ssl.o -c ssl.c

```
ssl.c:91:9: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
               ^
../openssl-1.1.0-pre6/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:91:14: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
                    ^
../openssl-1.1.0-pre6/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:91:19: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
                         ^
../openssl-1.1.0-pre6/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:91:22: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
                            ^
../openssl-1.1.0-pre6/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:101:2: warning: implicit declaration of function 'BN_init' is invalid in C99 [-Wimplicit-function-declaration]
        BN_init(&mod);
        ^
ssl.c:149:24: error: incomplete definition of type 'struct x509_st'
        nid = OBJ_obj2nid(cert->cert_info->key->algor->algorithm);
                          ~~~~^
../openssl-1.1.0-pre6/include/openssl/ossl_typ.h:119:16: note: forward declaration of 'struct x509_st'
typedef struct x509_st X509;
               ^
```
##

**Comment by milljm** [comment]
Same for me. El Capitan 10.11.6 / Xcode Command Line Tools 7.3.1
Trying to build using the rdesktop-1.8.3.tar.gz release tarball.

```bash
[] > export CC=clang; export CXX=clang++
[] > clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)
[] > ./configure --enable-smartcard --disable-credssp
...
checking for gcc... clang
checking for OpenSSL directory... /usr/local/openssl
...
## Using OpenSSL 1.1.0

[] > make
make
...
...
...
clang -g -O2 -Wall -I/usr/local/openssl/include    -I/usr/X11/include -DPACKAGE_NAME=\"rdesktop\" -DPACKAGE_TARNAME=\"rdesktop\" -DPACKAGE_VERSION=\"1.8.3\" -DPACKAGE_STRING=\"rdesktop\ 1.8.3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DL_ENDIAN=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_SYS_FILIO_H=1 -DHAVE_LOCALE_H=1 -DHAVE_LANGINFO_H=1 -DHAVE_SYSEXITS_H=1 -Dssldir=\"/usr/local/openssl\" -DWITH_SCARD=1 -DEGD_SOCKET=\"/var/run/egd-pool\" -DWITH_RDPSND=1 -DHAVE_DIRENT_H=1 -DHAVE_DIRFD=1 -DHAVE_DECL_DIRFD=1 -DHAVE_ICONV_H=1 -DHAVE_ICONV=1 -DICONV_CONST= -DHAVE_SYS_STATVFS_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_MOUNT_H=1 -DSTAT_STATVFS=1 -DHAVE_STRUCT_STATVFS_F_NAMEMAX=1 -DKEYMAP_PATH=\"/usr/local/share/rdesktop/keymaps/\" -o ssl.o -c ssl.c
ssl.c:91:9: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
               ^
/usr/local/openssl/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:91:14: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
                    ^
/usr/local/openssl/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:91:19: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
                         ^
/usr/local/openssl/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:91:22: error: variable has incomplete type 'BIGNUM' (aka 'struct bignum_st')
        BIGNUM mod, exp, x, y;
                            ^
/usr/local/openssl/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'struct bignum_st'
typedef struct bignum_st BIGNUM;
               ^
ssl.c:101:2: warning: implicit declaration of function 'BN_init' is invalid in C99 [-Wimplicit-function-declaration]
        BN_init(&mod);
        ^
ssl.c:149:24: error: incomplete definition of type 'struct x509_st'
        nid = OBJ_obj2nid(cert->cert_info->key->algor->algorithm);
                          ~~~~^
/usr/local/openssl/include/openssl/ossl_typ.h:119:16: note: forward declaration of 'struct x509_st'
typedef struct x509_st X509;
               ^
ssl.c:153:24: error: incomplete definition of type 'struct x509_st'
                ASN1_OBJECT_free(cert->cert_info->key->algor->algorithm);
                                 ~~~~^
/usr/local/openssl/include/openssl/ossl_typ.h:119:16: note: forward declaration of 'struct x509_st'
typedef struct x509_st X509;
               ^
ssl.c:154:7: error: incomplete definition of type 'struct x509_st'
                cert->cert_info->key->algor->algorithm = OBJ_nid2obj(NID_rsaEncryption);
                ~~~~^
/usr/local/openssl/include/openssl/ossl_typ.h:119:16: note: forward declaration of 'struct x509_st'
typedef struct x509_st X509;
               ^
ssl.c:204:24: error: incomplete definition of type 'struct rsa_st'
        if ((BN_num_bytes(rkey->e) > (int) max_exp_len) ||
                          ~~~~^
/usr/local/openssl/include/openssl/bn.h:142:40: note: expanded from macro 'BN_num_bytes'
# define BN_num_bytes(a) ((BN_num_bits(a)+7)/8)
                                       ^
/usr/local/openssl/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
ssl.c:205:24: error: incomplete definition of type 'struct rsa_st'
            (BN_num_bytes(rkey->n) > (int) max_mod_len))
                          ~~~~^
/usr/local/openssl/include/openssl/bn.h:142:40: note: expanded from macro 'BN_num_bytes'
# define BN_num_bytes(a) ((BN_num_bits(a)+7)/8)
                                       ^
/usr/local/openssl/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
ssl.c:209:22: error: incomplete definition of type 'struct rsa_st'
        len = BN_bn2bin(rkey->e, exponent);
                        ~~~~^
/usr/local/openssl/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
ssl.c:211:22: error: incomplete definition of type 'struct rsa_st'
        len = BN_bn2bin(rkey->n, modulus);
                        ~~~~^
/usr/local/openssl/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
ssl.c:232:11: error: variable has incomplete type 'HMAC_CTX' (aka 'struct hmac_ctx_st')
        HMAC_CTX ctx;
                 ^
/usr/local/openssl/include/openssl/ossl_typ.h:102:16: note: forward declaration of 'struct hmac_ctx_st'
typedef struct hmac_ctx_st HMAC_CTX;
               ^
ssl.c:233:2: warning: implicit declaration of function 'HMAC_CTX_init' is invalid in C99 [-Wimplicit-function-declaration]
        HMAC_CTX_init(&ctx);
        ^
ssl.c:235:2: warning: implicit declaration of function 'HMAC_CTX_cleanup' is invalid in C99 [-Wimplicit-function-declaration]
        HMAC_CTX_cleanup(&ctx);
        ^
3 warnings and 12 errors generated.
make: *** [ssl.o] Error 1
```

**Comment by hean01-cendio** [comment]
This seems to be a OpenSSL 1.1.x problem. You can test the pull request #44 and see if it solves your problem. As mentioned on the PR OpenSSL 1.1.0 "was" beta at the time and is now released 25 august. So it will be included in the upcoming release of rdesktop.

**Comment by hean01-cendio** [comment]
Closing this issue due to this seems to be related to OpenSSL 1.1.x compability which is added when merging pull request #44.
